#!/usr/bin/env python3
"""Create the packaging-verified C report without mutating the source artifact."""

from __future__ import annotations

import sys
import uuid
import re
from hashlib import sha256
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo


REPLACEMENTS = {
    "Source Han Sans CN": "Noto Sans CJK SC",
    "Scientific Discovery Report v1.9 · A/B 验收与发布身份对齐版":
        "Scientific Discovery Report v1.10 · 包装验收与发布版",
    "OBS Trust Layer · EXP17 · v1.9": "OBS Trust Layer · EXP17 · v1.10",
    "goai-2026-final-v2": "goai-2026-final-v3",
    "OBS 可信 AI 调度层 — Scientific Discovery Report v1.9":
        "OBS 可信 AI 调度层 — Scientific Discovery Report v1.10",
    "A/B delivery acceptance, final EXP17 adjudication language, and release identity":
        "Packaging-verified EXP17 scientific report and release identity",
    "<cp:lastModifiedBy>Qiyue Wu</cp:lastModifiedBy>":
        "<cp:lastModifiedBy>OBS Trust Engine Team</cp:lastModifiedBy>",
    "<dc:description>generated by python-docx</dc:description>":
        "<dc:description>Packaging-verified semifinal scientific report</dc:description>",
    "<Pages>14</Pages>": "<Pages>12</Pages>",
    "A/B 交付候选 a6c5f1f；C 审阅基线 003a1e7":
        "工程提交候选 a6c5f1f；科研证据审阅基线 003a1e7",
    "A/B 交付候选基线为 a6c5f1f；C 的科学表述、来源与许可证披露复核基线为 003a1e7":
        "工程提交候选基线为 a6c5f1f；科学表述、来源与许可证披露复核基线为 003a1e7",
    "A/B 交付验收确认": "工程与证据交付验收确认",
}

FONT_NAME = "Noto Sans CJK SC"
FONT_REL_ID = "rIdNotoSansCJKSC"
FONT_PART = "word/fonts/NotoSansCJKsc-Regular.odttf"
FONT_REL_TARGET = "fonts/NotoSansCJKsc-Regular.odttf"
REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"
FONT_REL_TYPE = (
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/font"
)


def obfuscate_font(font_data: bytes, font_key: uuid.UUID) -> bytes:
    """Apply the ECMA-376 font obfuscation to the first 32 bytes."""
    key = list(font_key.bytes)
    key.reverse()
    output = bytearray(font_data)
    for index in range(min(32, len(output))):
        output[index] ^= key[index % 16]
    return bytes(output)


def mark_table_headers(document_xml: bytes) -> bytes:
    """Mark the first row of each non-nested report table as a header row."""
    text = document_xml.decode("utf-8")
    table_pattern = re.compile(r"<w:tbl(?:\s[^>]*)?>.*?</w:tbl>", re.DOTALL)

    def fix_table(match: re.Match[str]) -> str:
        table = match.group(0)
        row_match = re.search(
            r"(<w:tr(?:\s[^>]*)?>)(.*?)(</w:tr>)", table, re.DOTALL
        )
        if not row_match or "<w:tblHeader" in row_match.group(0):
            return table

        row = row_match.group(0)
        if "<w:trPr" in row:
            row = re.sub(
                r"(<w:trPr(?:\s[^>]*)?>)",
                r"\1<w:tblHeader/>",
                row,
                count=1,
            )
        else:
            row = row.replace(
                row_match.group(1),
                f"{row_match.group(1)}<w:trPr><w:tblHeader/></w:trPr>",
                1,
            )
        return table[: row_match.start()] + row + table[row_match.end() :]

    return table_pattern.sub(fix_table, text).encode("utf-8")


def add_embedded_font(parts: dict[str, bytes], font_path: Path) -> None:
    if not font_path.is_file():
        raise SystemExit(f"Embedded font not found: {font_path}")

    font_data = font_path.read_bytes()
    if len(font_data) < 32:
        raise SystemExit(f"Embedded font is invalid: {font_path}")

    digest = sha256(font_data).hexdigest()
    font_key = uuid.uuid5(uuid.NAMESPACE_URL, f"goai:noto-cjk-sc:{digest}")
    parts[FONT_PART] = obfuscate_font(font_data, font_key)

    font_table = parts["word/fontTable.xml"].decode("utf-8")
    embed = (
        f'<w:font w:name="{FONT_NAME}">'
        '<w:charset w:val="86"/><w:family w:val="swiss"/>'
        '<w:pitch w:val="variable"/>'
        f'<w:embedRegular r:id="{FONT_REL_ID}" '
        f'w:fontKey="{{{str(font_key).upper()}}}" w:subsetted="false"/>'
        '</w:font>'
    )
    if f'w:name="{FONT_NAME}"' not in font_table:
        font_table = font_table.replace("</w:fonts>", f"{embed}</w:fonts>")
    elif "w:embedRegular" not in font_table:
        font_table = font_table.replace(
            f'<w:font w:name="{FONT_NAME}">',
            f'<w:font w:name="{FONT_NAME}"><w:embedRegular '
            f'r:id="{FONT_REL_ID}" w:fontKey="{{{str(font_key).upper()}}}" '
            'w:subsetted="false"/>',
            1,
        )
    parts["word/fontTable.xml"] = font_table.encode("utf-8")

    rels_name = "word/_rels/fontTable.xml.rels"
    rels = parts.get(
        rels_name,
        (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            f'<Relationships xmlns="{REL_NS}"></Relationships>'
        ).encode("utf-8"),
    ).decode("utf-8")
    if FONT_REL_ID not in rels:
        relationship = (
            f'<Relationship Id="{FONT_REL_ID}" Type="{FONT_REL_TYPE}" '
            f'Target="{FONT_REL_TARGET}"/>'
        )
        rels = rels.replace("</Relationships>", f"{relationship}</Relationships>")
    parts[rels_name] = rels.encode("utf-8")

    content_types = parts["[Content_Types].xml"].decode("utf-8")
    if 'Extension="odttf"' not in content_types:
        default = (
            '<Default Extension="odttf" '
            'ContentType="application/vnd.openxmlformats-officedocument.obfuscatedFont"/>'
        )
        content_types = content_types.replace("</Types>", f"{default}</Types>")
    parts["[Content_Types].xml"] = content_types.encode("utf-8")

    settings = parts["word/settings.xml"].decode("utf-8")
    if "<w:embedTrueTypeFonts" not in settings:
        settings = settings.replace(
            "</w:settings>", "<w:embedTrueTypeFonts/></w:settings>"
        )
    parts["word/settings.xml"] = settings.encode("utf-8")


def revise(input_path: Path, output_path: Path, font_path: Path) -> None:
    if input_path.resolve() == output_path.resolve():
        raise SystemExit("Refusing to overwrite the source DOCX")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with ZipFile(input_path, "r") as zin:
        source_infos = {info.filename: info for info in zin.infolist()}
        parts = {info.filename: zin.read(info.filename) for info in zin.infolist()}

    for filename, payload in list(parts.items()):
        if filename.endswith((".xml", ".rels")):
            text = payload.decode("utf-8")
            for old, new in REPLACEMENTS.items():
                text = text.replace(old, new)
            parts[filename] = text.encode("utf-8")

    parts["word/document.xml"] = mark_table_headers(parts["word/document.xml"])

    add_embedded_font(parts, font_path)

    with ZipFile(output_path, "w", ZIP_DEFLATED) as zout:
        for filename, payload in parts.items():
            info = source_infos.get(filename)
            date_time = info.date_time if info else (2026, 9, 2, 0, 0, 0)
            new_info = ZipInfo(filename, date_time=date_time)
            new_info.compress_type = ZIP_DEFLATED
            if info:
                new_info.external_attr = info.external_attr
                new_info.comment = info.comment
                new_info.create_system = info.create_system
            zout.writestr(new_info, payload)


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit(
            "usage: revise_final_docx.py INPUT.docx OUTPUT.docx FONT.otf"
        )
    revise(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]))


if __name__ == "__main__":
    main()
